#DCRandomTP ~ Created by PimpDuck#
#Cooldown is in hours#
DCRandomTP:
  Message: "&bPlease wait while we find you a safe location."
  Chat-Prefix:  " &f[&bDC&cRandom&bTP&f] " 
  World: World
  Min-x: 1
  Max-x: 3000
  Min-z: 1
  Max-z: 3000
  
  Options:
    Cooldown: 6
