name: DCRandomTP
main: me.PimpDuck.DCRandomTP.Main
version: 1.0
commands:
   random:
     description: Tp to a random location.
permissions:
   dcrandomtp.tp:
     description: Allows you to tp to a random location.
     default: true
